name: Deploy Obsidian Files

# Trigger on push to main branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install
        working-directory: scripts

      - name: Build site
        run: yarn build
        working-directory: scripts

      - name: Deploy
        run: |
          # Sync built site to nginx
          rsync -avz --delete _site/ /var/www/dnd/

          # Fix permissions so Nginx can read
          sudo chown -R deploy-web:www-data /var/www/dnd/
          sudo chmod -R 775 /var/www/dnd/

          # Reload Nginx to serve the new build
          sudo systemctl reload nginx