name: Deploy Obsidian Files

# Trigger on push to main branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Obsidian content
        uses: actions/checkout@v3
        with:
          path: obsidian-content

      - name: Test access to Quartz repo
        run: |
          git ls-remote https://${{ secrets.QUARTZ_ACCESS_TOKEN }}@github.com/freiha-org/quartz-obsidian-client.git

      - name: Checkout custom Quartz
        uses: actions/checkout@v3
        with:
          repository: freiha-org/quartz-obsidian-client
          path: quartz
          token: ${{ secrets.QUARTZ_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'

      - name: Build Quartz
        run: |
          cd quartz
          npm install
          npx quartz build

      - name: Deploy
        run: |
          # Sync built site to nginx
          sudo rm -rf /var/www/dnd/*
          sudo cp -r quartz/public/* /var/www/dnd/

          # Fix permissions so Nginx can read
          sudo chown -R deploy-web:www-data /var/www/dnd/
          sudo chmod -R 775 /var/www/dnd/

          # Reload Nginx to serve the new build
          sudo systemctl reload nginx